spring: 
 datasource:
  url: {{DB_URL}}
  driverClassName: {{DRIVER_CLASS}}
  username: {{USER_NAME}}
  password: {{PASS_WORD}}
  initialization-mode: embedded
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
   hibernate:
    generate_statistics: false
    format_sql: true
    ddl-auto: none
    show_sql: true
 h2:
  console: 
   enabled: true
eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: false
      fetchRegistry: false
server:
  port : 8082
  
testapi:
  endpoint: {{TEST_URL}}
  key: {{TEST_KEY}}
